# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PythIon\Designer Files\plotgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PythIon(object):
    def setupUi(self, PythIon):
        PythIon.setObjectName("PythIon")
        PythIon.resize(1549, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PythIon.sizePolicy().hasHeightForWidth())
        PythIon.setSizePolicy(sizePolicy)
        PythIon.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pythionlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PythIon.setWindowIcon(icon)
        PythIon.setAutoFillBackground(False)
        PythIon.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(PythIon)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_10.setHorizontalSpacing(15)
        self.gridLayout_10.setVerticalSpacing(10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.control_panel_container = QtWidgets.QHBoxLayout()
        self.control_panel_container.setObjectName("control_panel_container")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(175, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.load_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        self.load_button.setMinimumSize(QtCore.QSize(70, 0))
        self.load_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.load_button.setFont(font)
        self.load_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.load_button.setAutoFillBackground(False)
        self.load_button.setObjectName("load_button")
        self.gridLayout_2.addWidget(self.load_button, 1, 0, 1, 1)
        self.previous_file_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_file_button.sizePolicy().hasHeightForWidth())
        self.previous_file_button.setSizePolicy(sizePolicy)
        self.previous_file_button.setMinimumSize(QtCore.QSize(70, 0))
        self.previous_file_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.previous_file_button.setFont(font)
        self.previous_file_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previous_file_button.setAutoFillBackground(False)
        self.previous_file_button.setObjectName("previous_file_button")
        self.gridLayout_2.addWidget(self.previous_file_button, 3, 0, 1, 1)
        self.invert_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invert_button.sizePolicy().hasHeightForWidth())
        self.invert_button.setSizePolicy(sizePolicy)
        self.invert_button.setMinimumSize(QtCore.QSize(70, 0))
        self.invert_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.invert_button.setFont(font)
        self.invert_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.invert_button.setAutoFillBackground(False)
        self.invert_button.setObjectName("invert_button")
        self.gridLayout_2.addWidget(self.invert_button, 5, 1, 1, 1)
        self.next_file_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_file_button.sizePolicy().hasHeightForWidth())
        self.next_file_button.setSizePolicy(sizePolicy)
        self.next_file_button.setMinimumSize(QtCore.QSize(70, 0))
        self.next_file_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.next_file_button.setFont(font)
        self.next_file_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.next_file_button.setAutoFillBackground(False)
        self.next_file_button.setObjectName("next_file_button")
        self.gridLayout_2.addWidget(self.next_file_button, 3, 1, 1, 1)
        self.baseline_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseline_button.sizePolicy().hasHeightForWidth())
        self.baseline_button.setSizePolicy(sizePolicy)
        self.baseline_button.setMinimumSize(QtCore.QSize(70, 0))
        self.baseline_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.baseline_button.setFont(font)
        self.baseline_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baseline_button.setAutoFillBackground(False)
        self.baseline_button.setObjectName("baseline_button")
        self.gridLayout_2.addWidget(self.baseline_button, 5, 0, 1, 1)
        self.clear_data_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_data_button.sizePolicy().hasHeightForWidth())
        self.clear_data_button.setSizePolicy(sizePolicy)
        self.clear_data_button.setMinimumSize(QtCore.QSize(70, 5))
        self.clear_data_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.clear_data_button.setFont(font)
        self.clear_data_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear_data_button.setAutoFillBackground(False)
        self.clear_data_button.setObjectName("clear_data_button")
        self.gridLayout_2.addWidget(self.clear_data_button, 1, 1, 1, 1)
        self.cut_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cut_button.sizePolicy().hasHeightForWidth())
        self.cut_button.setSizePolicy(sizePolicy)
        self.cut_button.setMinimumSize(QtCore.QSize(70, 5))
        self.cut_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cut_button.setFont(font)
        self.cut_button.setToolTipDuration(-1)
        self.cut_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cut_button.setAutoFillBackground(False)
        self.cut_button.setObjectName("cut_button")
        self.gridLayout_2.addWidget(self.cut_button, 7, 0, 1, 1)
        self.analyze_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyze_button.sizePolicy().hasHeightForWidth())
        self.analyze_button.setSizePolicy(sizePolicy)
        self.analyze_button.setMinimumSize(QtCore.QSize(70, 0))
        self.analyze_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.analyze_button.setFont(font)
        self.analyze_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analyze_button.setAutoFillBackground(False)
        self.analyze_button.setObjectName("analyze_button")
        self.gridLayout_2.addWidget(self.analyze_button, 7, 1, 1, 1)
        self.control_panel_container.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 150))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.low_pass_filter_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_pass_filter_label.sizePolicy().hasHeightForWidth())
        self.low_pass_filter_label.setSizePolicy(sizePolicy)
        self.low_pass_filter_label.setMinimumSize(QtCore.QSize(150, 20))
        self.low_pass_filter_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.low_pass_filter_label.setFont(font)
        self.low_pass_filter_label.setObjectName("low_pass_filter_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.low_pass_filter_label)
        self.low_pass_entry = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_pass_entry.sizePolicy().hasHeightForWidth())
        self.low_pass_entry.setSizePolicy(sizePolicy)
        self.low_pass_entry.setMinimumSize(QtCore.QSize(80, 20))
        self.low_pass_entry.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.low_pass_entry.setFont(font)
        self.low_pass_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.low_pass_entry.setObjectName("low_pass_entry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.low_pass_entry)
        self.sample_rate_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_rate_label.sizePolicy().hasHeightForWidth())
        self.sample_rate_label.setSizePolicy(sizePolicy)
        self.sample_rate_label.setMinimumSize(QtCore.QSize(150, 20))
        self.sample_rate_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sample_rate_label.setFont(font)
        self.sample_rate_label.setObjectName("sample_rate_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sample_rate_label)
        self.sample_rate_entry = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_rate_entry.sizePolicy().hasHeightForWidth())
        self.sample_rate_entry.setSizePolicy(sizePolicy)
        self.sample_rate_entry.setMinimumSize(QtCore.QSize(80, 20))
        self.sample_rate_entry.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sample_rate_entry.setFont(font)
        self.sample_rate_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_rate_entry.setObjectName("sample_rate_entry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sample_rate_entry)
        self.event_buffer_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_buffer_label.sizePolicy().hasHeightForWidth())
        self.event_buffer_label.setSizePolicy(sizePolicy)
        self.event_buffer_label.setMinimumSize(QtCore.QSize(150, 20))
        self.event_buffer_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.event_buffer_label.setFont(font)
        self.event_buffer_label.setObjectName("event_buffer_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.event_buffer_label)
        self.event_buffer_entry = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_buffer_entry.sizePolicy().hasHeightForWidth())
        self.event_buffer_entry.setSizePolicy(sizePolicy)
        self.event_buffer_entry.setMinimumSize(QtCore.QSize(80, 20))
        self.event_buffer_entry.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.event_buffer_entry.setFont(font)
        self.event_buffer_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.event_buffer_entry.setObjectName("event_buffer_entry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.event_buffer_entry)
        self.threshold_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_label.sizePolicy().hasHeightForWidth())
        self.threshold_label.setSizePolicy(sizePolicy)
        self.threshold_label.setMinimumSize(QtCore.QSize(150, 20))
        self.threshold_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("threshold_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.threshold_label)
        self.threshold_entry = QtWidgets.QLineEdit(self.groupBox_2)
        self.threshold_entry.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_entry.sizePolicy().hasHeightForWidth())
        self.threshold_entry.setSizePolicy(sizePolicy)
        self.threshold_entry.setMinimumSize(QtCore.QSize(80, 20))
        self.threshold_entry.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.threshold_entry.setFont(font)
        self.threshold_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_entry.setObjectName("threshold_entry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.threshold_entry)
        self.control_panel_container.addWidget(self.groupBox_2)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(150, 150))
        self.groupBox1.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.file_label = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_label.sizePolicy().hasHeightForWidth())
        self.file_label.setSizePolicy(sizePolicy)
        self.file_label.setMinimumSize(QtCore.QSize(500, 10))
        self.file_label.setMaximumSize(QtCore.QSize(3000, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.file_label.setFont(font)
        self.file_label.setText("")
        self.file_label.setObjectName("file_label")
        self.gridLayout_11.addWidget(self.file_label, 3, 0, 1, 2)
        self.event_selector = QtWidgets.QGroupBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_selector.sizePolicy().hasHeightForWidth())
        self.event_selector.setSizePolicy(sizePolicy)
        self.event_selector.setMinimumSize(QtCore.QSize(225, 75))
        self.event_selector.setMaximumSize(QtCore.QSize(16777215, 50))
        self.event_selector.setAlignment(QtCore.Qt.AlignCenter)
        self.event_selector.setObjectName("event_selector")
        self.event_selector_layout = QtWidgets.QVBoxLayout(self.event_selector)
        self.event_selector_layout.setContentsMargins(5, 0, 5, 5)
        self.event_selector_layout.setObjectName("event_selector_layout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, -1, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.previous_event_button = QtWidgets.QPushButton(self.event_selector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_event_button.sizePolicy().hasHeightForWidth())
        self.previous_event_button.setSizePolicy(sizePolicy)
        self.previous_event_button.setMinimumSize(QtCore.QSize(0, 5))
        self.previous_event_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.previous_event_button.setFont(font)
        self.previous_event_button.setObjectName("previous_event_button")
        self.gridLayout.addWidget(self.previous_event_button, 1, 1, 1, 1)
        self.next_event_button = QtWidgets.QPushButton(self.event_selector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_event_button.sizePolicy().hasHeightForWidth())
        self.next_event_button.setSizePolicy(sizePolicy)
        self.next_event_button.setMinimumSize(QtCore.QSize(0, 5))
        self.next_event_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.next_event_button.setFont(font)
        self.next_event_button.setObjectName("next_event_button")
        self.gridLayout.addWidget(self.next_event_button, 1, 3, 1, 1)
        self.go_event_button = QtWidgets.QPushButton(self.event_selector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_event_button.sizePolicy().hasHeightForWidth())
        self.go_event_button.setSizePolicy(sizePolicy)
        self.go_event_button.setMinimumSize(QtCore.QSize(0, 5))
        self.go_event_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.go_event_button.setFont(font)
        self.go_event_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.go_event_button.setObjectName("go_event_button")
        self.gridLayout.addWidget(self.go_event_button, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.event_number_entry = QtWidgets.QLineEdit(self.event_selector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_number_entry.sizePolicy().hasHeightForWidth())
        self.event_number_entry.setSizePolicy(sizePolicy)
        self.event_number_entry.setMinimumSize(QtCore.QSize(50, 0))
        self.event_number_entry.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.event_number_entry.setFont(font)
        self.event_number_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.event_number_entry.setObjectName("event_number_entry")
        self.gridLayout.addWidget(self.event_number_entry, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.event_selector)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 2)
        self.event_selector_layout.addLayout(self.gridLayout)
        self.gridLayout_11.addWidget(self.event_selector, 0, 1, 1, 1)
        self.control_panel_container.addWidget(self.groupBox1)
        self.cat_button_group = QtWidgets.QGroupBox(self.centralwidget)
        self.cat_button_group.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat_button_group.sizePolicy().hasHeightForWidth())
        self.cat_button_group.setSizePolicy(sizePolicy)
        self.cat_button_group.setMinimumSize(QtCore.QSize(125, 150))
        self.cat_button_group.setMaximumSize(QtCore.QSize(125, 150))
        self.cat_button_group.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cat_button_group.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cat_button_group.setFlat(False)
        self.cat_button_group.setCheckable(False)
        self.cat_button_group.setObjectName("cat_button_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cat_button_group)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.delete_event_button = QtWidgets.QPushButton(self.cat_button_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_event_button.sizePolicy().hasHeightForWidth())
        self.delete_event_button.setSizePolicy(sizePolicy)
        self.delete_event_button.setMinimumSize(QtCore.QSize(100, 20))
        self.delete_event_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.delete_event_button.setFont(font)
        self.delete_event_button.setObjectName("delete_event_button")
        self.gridLayout_5.addWidget(self.delete_event_button, 0, 0, 1, 1)
        self.concatenate_button = QtWidgets.QPushButton(self.cat_button_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concatenate_button.sizePolicy().hasHeightForWidth())
        self.concatenate_button.setSizePolicy(sizePolicy)
        self.concatenate_button.setMinimumSize(QtCore.QSize(100, 20))
        self.concatenate_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.concatenate_button.setFont(font)
        self.concatenate_button.setObjectName("concatenate_button")
        self.gridLayout_5.addWidget(self.concatenate_button, 1, 0, 1, 1)
        self.save_event_fits_button = QtWidgets.QPushButton(self.cat_button_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_event_fits_button.sizePolicy().hasHeightForWidth())
        self.save_event_fits_button.setSizePolicy(sizePolicy)
        self.save_event_fits_button.setMinimumSize(QtCore.QSize(100, 20))
        self.save_event_fits_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.save_event_fits_button.setFont(font)
        self.save_event_fits_button.setObjectName("save_event_fits_button")
        self.gridLayout_5.addWidget(self.save_event_fits_button, 2, 0, 1, 1)
        self.control_panel_container.addWidget(self.cat_button_group, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.gridLayout_10.addLayout(self.control_panel_container, 0, 1, 1, 1)
        self.signal_plot = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signal_plot.sizePolicy().hasHeightForWidth())
        self.signal_plot.setSizePolicy(sizePolicy)
        self.signal_plot.setMinimumSize(QtCore.QSize(0, 225))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signal_plot.setFont(font)
        self.signal_plot.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.signal_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signal_plot.setObjectName("signal_plot")
        self.gridLayout_10.addWidget(self.signal_plot, 1, 1, 1, 1)
        self.event_and_signal_container = QtWidgets.QHBoxLayout()
        self.event_and_signal_container.setContentsMargins(0, -1, 0, -1)
        self.event_and_signal_container.setSpacing(5)
        self.event_and_signal_container.setObjectName("event_and_signal_container")
        self.event_plot = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_plot.sizePolicy().hasHeightForWidth())
        self.event_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.event_plot.setFont(font)
        self.event_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";\n"
"border-color: rgb(0, 0, 0);")
        self.event_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.event_plot.setObjectName("event_plot")
        self.event_and_signal_container.addWidget(self.event_plot)
        self.tab_plot_widget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_plot_widget.sizePolicy().hasHeightForWidth())
        self.tab_plot_widget.setSizePolicy(sizePolicy)
        self.tab_plot_widget.setMaximumSize(QtCore.QSize(16777215, 16777206))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.tab_plot_widget.setFont(font)
        self.tab_plot_widget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tab_plot_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_plot_widget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tab_plot_widget.setDocumentMode(False)
        self.tab_plot_widget.setObjectName("tab_plot_widget")
        self.scatter_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.scatter_tab.setFont(font)
        self.scatter_tab.setObjectName("scatter_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scatter_tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scatter_plot = GraphicsLayoutWidget(self.scatter_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatter_plot.sizePolicy().hasHeightForWidth())
        self.scatter_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.scatter_plot.setFont(font)
        self.scatter_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.scatter_plot.setObjectName("scatter_plot")
        self.gridLayout_3.addWidget(self.scatter_plot, 0, 0, 1, 1)
        self.tab_plot_widget.addTab(self.scatter_tab, "")
        self.frac_tab = QtWidgets.QWidget()
        self.frac_tab.setObjectName("frac_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frac_tab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frac_plot = GraphicsLayoutWidget(self.frac_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frac_plot.sizePolicy().hasHeightForWidth())
        self.frac_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.frac_plot.setFont(font)
        self.frac_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.frac_plot.setObjectName("frac_plot")
        self.gridLayout_6.addWidget(self.frac_plot, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frac_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.fracbins = QtWidgets.QLineEdit(self.frac_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fracbins.sizePolicy().hasHeightForWidth())
        self.fracbins.setSizePolicy(sizePolicy)
        self.fracbins.setAlignment(QtCore.Qt.AlignCenter)
        self.fracbins.setObjectName("fracbins")
        self.horizontalLayout_2.addWidget(self.fracbins)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tab_plot_widget.addTab(self.frac_tab, "")
        self.del_i_tab = QtWidgets.QWidget()
        self.del_i_tab.setObjectName("del_i_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.del_i_tab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.del_i_plot = GraphicsLayoutWidget(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_i_plot.sizePolicy().hasHeightForWidth())
        self.del_i_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.del_i_plot.setFont(font)
        self.del_i_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.del_i_plot.setObjectName("del_i_plot")
        self.gridLayout_7.addWidget(self.del_i_plot, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.del_i_tab)
        self.label_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.delibins = QtWidgets.QLineEdit(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delibins.sizePolicy().hasHeightForWidth())
        self.delibins.setSizePolicy(sizePolicy)
        self.delibins.setAlignment(QtCore.Qt.AlignCenter)
        self.delibins.setObjectName("delibins")
        self.horizontalLayout_7.addWidget(self.delibins)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.delirange0 = QtWidgets.QLineEdit(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange0.sizePolicy().hasHeightForWidth())
        self.delirange0.setSizePolicy(sizePolicy)
        self.delirange0.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange0.setObjectName("delirange0")
        self.horizontalLayout_9.addWidget(self.delirange0)
        self.label_12 = QtWidgets.QLabel(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.delirange1 = QtWidgets.QLineEdit(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange1.sizePolicy().hasHeightForWidth())
        self.delirange1.setSizePolicy(sizePolicy)
        self.delirange1.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange1.setObjectName("delirange1")
        self.horizontalLayout_9.addWidget(self.delirange1)
        self.label_11 = QtWidgets.QLabel(self.del_i_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tab_plot_widget.addTab(self.del_i_tab, "")
        self.dwell_tab = QtWidgets.QWidget()
        self.dwell_tab.setObjectName("dwell_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dwell_tab)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dwell_plot = GraphicsLayoutWidget(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwell_plot.sizePolicy().hasHeightForWidth())
        self.dwell_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dwell_plot.setFont(font)
        self.dwell_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dwell_plot.setObjectName("dwell_plot")
        self.gridLayout_8.addWidget(self.dwell_plot, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.dwellbins = QtWidgets.QLineEdit(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellbins.sizePolicy().hasHeightForWidth())
        self.dwellbins.setSizePolicy(sizePolicy)
        self.dwellbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellbins.setObjectName("dwellbins")
        self.horizontalLayout_14.addWidget(self.dwellbins)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.dwellrange0 = QtWidgets.QLineEdit(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange0.sizePolicy().hasHeightForWidth())
        self.dwellrange0.setSizePolicy(sizePolicy)
        self.dwellrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange0.setObjectName("dwellrange0")
        self.horizontalLayout_10.addWidget(self.dwellrange0)
        self.label_23 = QtWidgets.QLabel(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.dwellrange1 = QtWidgets.QLineEdit(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange1.sizePolicy().hasHeightForWidth())
        self.dwellrange1.setSizePolicy(sizePolicy)
        self.dwellrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange1.setObjectName("dwellrange1")
        self.horizontalLayout_10.addWidget(self.dwellrange1)
        self.label_24 = QtWidgets.QLabel(self.dwell_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.tab_plot_widget.addTab(self.dwell_tab, "")
        self.dt_tab = QtWidgets.QWidget()
        self.dt_tab.setObjectName("dt_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dt_tab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.dt_plot = GraphicsLayoutWidget(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dt_plot.sizePolicy().hasHeightForWidth())
        self.dt_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dt_plot.setFont(font)
        self.dt_plot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dt_plot.setObjectName("dt_plot")
        self.gridLayout_9.addWidget(self.dt_plot, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.dtbins = QtWidgets.QLineEdit(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtbins.sizePolicy().hasHeightForWidth())
        self.dtbins.setSizePolicy(sizePolicy)
        self.dtbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dtbins.setObjectName("dtbins")
        self.horizontalLayout_18.addWidget(self.dtbins)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.dt_tab)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.dtrange0 = QtWidgets.QLineEdit(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange0.sizePolicy().hasHeightForWidth())
        self.dtrange0.setSizePolicy(sizePolicy)
        self.dtrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange0.setObjectName("dtrange0")
        self.horizontalLayout_19.addWidget(self.dtrange0)
        self.label_27 = QtWidgets.QLabel(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.dtrange1 = QtWidgets.QLineEdit(self.dt_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange1.sizePolicy().hasHeightForWidth())
        self.dtrange1.setSizePolicy(sizePolicy)
        self.dtrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange1.setObjectName("dtrange1")
        self.horizontalLayout_19.addWidget(self.dtrange1)
        self.label_28 = QtWidgets.QLabel(self.dt_tab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.tab_plot_widget.addTab(self.dt_tab, "")
        self.event_and_signal_container.addWidget(self.tab_plot_widget)
        self.gridLayout_10.addLayout(self.event_and_signal_container, 3, 1, 1, 1)
        PythIon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PythIon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1549, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.edit_menu = QtWidgets.QMenu(self.menubar)
        self.edit_menu.setObjectName("edit_menu")
        PythIon.setMenuBar(self.menubar)
        self.status_bar = QtWidgets.QStatusBar(PythIon)
        self.status_bar.setObjectName("status_bar")
        PythIon.setStatusBar(self.status_bar)
        self.actionInvert = QtWidgets.QAction(PythIon)
        self.actionInvert.setObjectName("actionInvert")
        self.actionsetbuffer = QtWidgets.QAction(PythIon)
        self.actionsetbuffer.setObjectName("actionsetbuffer")
        self.pore_sizer_action = QtWidgets.QAction(PythIon)
        self.pore_sizer_action.setObjectName("pore_sizer_action")
        self.batch_process_action = QtWidgets.QAction(PythIon)
        self.batch_process_action.setObjectName("batch_process_action")
        self.menuFile.addAction(self.pore_sizer_action)
        self.menuFile.addAction(self.batch_process_action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())

        self.retranslateUi(PythIon)
        self.tab_plot_widget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(PythIon)
        PythIon.setTabOrder(self.load_button, self.low_pass_entry)
        PythIon.setTabOrder(self.low_pass_entry, self.sample_rate_entry)
        PythIon.setTabOrder(self.sample_rate_entry, self.event_buffer_entry)
        PythIon.setTabOrder(self.event_buffer_entry, self.threshold_entry)
        PythIon.setTabOrder(self.threshold_entry, self.previous_event_button)
        PythIon.setTabOrder(self.previous_event_button, self.next_event_button)
        PythIon.setTabOrder(self.next_event_button, self.go_event_button)
        PythIon.setTabOrder(self.go_event_button, self.event_number_entry)
        PythIon.setTabOrder(self.event_number_entry, self.delete_event_button)
        PythIon.setTabOrder(self.delete_event_button, self.concatenate_button)
        PythIon.setTabOrder(self.concatenate_button, self.save_event_fits_button)
        PythIon.setTabOrder(self.save_event_fits_button, self.event_plot)
        PythIon.setTabOrder(self.event_plot, self.tab_plot_widget)
        PythIon.setTabOrder(self.tab_plot_widget, self.scatter_plot)
        PythIon.setTabOrder(self.scatter_plot, self.frac_plot)
        PythIon.setTabOrder(self.frac_plot, self.fracbins)
        PythIon.setTabOrder(self.fracbins, self.del_i_plot)
        PythIon.setTabOrder(self.del_i_plot, self.delibins)
        PythIon.setTabOrder(self.delibins, self.delirange0)
        PythIon.setTabOrder(self.delirange0, self.delirange1)
        PythIon.setTabOrder(self.delirange1, self.dwell_plot)
        PythIon.setTabOrder(self.dwell_plot, self.dwellbins)
        PythIon.setTabOrder(self.dwellbins, self.dwellrange0)
        PythIon.setTabOrder(self.dwellrange0, self.dwellrange1)
        PythIon.setTabOrder(self.dwellrange1, self.dt_plot)
        PythIon.setTabOrder(self.dt_plot, self.dtbins)
        PythIon.setTabOrder(self.dtbins, self.dtrange0)
        PythIon.setTabOrder(self.dtrange0, self.dtrange1)

    def retranslateUi(self, PythIon):
        _translate = QtCore.QCoreApplication.translate
        PythIon.setWindowTitle(_translate("PythIon", "PythIon"))
        self.load_button.setText(_translate("PythIon", "LOAD"))
        self.previous_file_button.setText(_translate("PythIon", "PREVIOUS"))
        self.invert_button.setText(_translate("PythIon", "INVERT"))
        self.next_file_button.setText(_translate("PythIon", "NEXT"))
        self.baseline_button.setText(_translate("PythIon", "BASELINE"))
        self.clear_data_button.setText(_translate("PythIon", "CLEAR DATA"))
        self.cut_button.setText(_translate("PythIon", "CUT"))
        self.analyze_button.setText(_translate("PythIon", "ANALYZE"))
        self.low_pass_filter_label.setText(_translate("PythIon", "Low Pass Filter (Hz)"))
        self.low_pass_entry.setText(_translate("PythIon", "7500"))
        self.sample_rate_label.setText(_translate("PythIon", "Sample Rate (kHz)"))
        self.sample_rate_entry.setText(_translate("PythIon", "4166.67"))
        self.event_buffer_label.setText(_translate("PythIon", "Event Buffer (samples)"))
        self.event_buffer_entry.setText(_translate("PythIon", "1000"))
        self.threshold_label.setText(_translate("PythIon", "Threshold (nA)"))
        self.threshold_entry.setText(_translate("PythIon", ".3"))
        self.previous_event_button.setText(_translate("PythIon", "Previous"))
        self.next_event_button.setText(_translate("PythIon", "Next"))
        self.go_event_button.setText(_translate("PythIon", "Go"))
        self.event_number_entry.setText(_translate("PythIon", "0"))
        self.label_4.setText(_translate("PythIon", "Event Number:"))
        self.delete_event_button.setText(_translate("PythIon", "DELETE EVENT"))
        self.concatenate_button.setText(_translate("PythIon", "CONCATENATE"))
        self.save_event_fits_button.setText(_translate("PythIon", "SAVE EVENT FITS"))
        self.tab_plot_widget.setTabText(self.tab_plot_widget.indexOf(self.scatter_tab), _translate("PythIon", "Scatter"))
        self.label_7.setText(_translate("PythIon", "Bins:"))
        self.fracbins.setText(_translate("PythIon", "50"))
        self.tab_plot_widget.setTabText(self.tab_plot_widget.indexOf(self.frac_tab), _translate("PythIon", "Frac"))
        self.label_9.setText(_translate("PythIon", "Bins"))
        self.delibins.setText(_translate("PythIon", "50"))
        self.label_10.setText(_translate("PythIon", "("))
        self.delirange0.setText(_translate("PythIon", "0"))
        self.label_12.setText(_translate("PythIon", "-"))
        self.delirange1.setText(_translate("PythIon", "1"))
        self.label_11.setText(_translate("PythIon", ")"))
        self.tab_plot_widget.setTabText(self.tab_plot_widget.indexOf(self.del_i_tab), _translate("PythIon", "Deli"))
        self.label_21.setText(_translate("PythIon", "Bins"))
        self.dwellbins.setText(_translate("PythIon", "100"))
        self.label_22.setText(_translate("PythIon", "("))
        self.dwellrange0.setText(_translate("PythIon", "0"))
        self.label_23.setText(_translate("PythIon", "-"))
        self.dwellrange1.setText(_translate("PythIon", "5"))
        self.label_24.setText(_translate("PythIon", ")"))
        self.tab_plot_widget.setTabText(self.tab_plot_widget.indexOf(self.dwell_tab), _translate("PythIon", "Dwell"))
        self.label_25.setText(_translate("PythIon", "Bins"))
        self.dtbins.setText(_translate("PythIon", "100"))
        self.label_26.setText(_translate("PythIon", "("))
        self.dtrange0.setText(_translate("PythIon", "0"))
        self.label_27.setText(_translate("PythIon", "-"))
        self.dtrange1.setText(_translate("PythIon", "1"))
        self.label_28.setText(_translate("PythIon", ")"))
        self.tab_plot_widget.setTabText(self.tab_plot_widget.indexOf(self.dt_tab), _translate("PythIon", "dt"))
        self.menuFile.setTitle(_translate("PythIon", "File"))
        self.edit_menu.setTitle(_translate("PythIon", "Edit"))
        self.actionInvert.setText(_translate("PythIon", "Invert data"))
        self.actionsetbuffer.setText(_translate("PythIon", "Set Event Buffer Size"))
        self.pore_sizer_action.setText(_translate("PythIon", "PoreSizer"))
        self.batch_process_action.setText(_translate("PythIon", "Batch Process"))

from pyqtgraph import GraphicsLayoutWidget
